name: Deploy to EC2

on:
  push:
    branches: [ main ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Add EC2 host to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 54.159.144.181 >> ~/.ssh/known_hosts
    
    - name: Deploy to EC2
      run: |
        echo "Deploying to ec2-user@54.159.144.181"
        ssh ec2-user@54.159.144.181 "
        mkdir -p ~/movie-app-server
        cd ~/movie-app-server
        
        if [ -d .git ]; then
          git pull
        else
          rm -rf *
          git clone ${{ github.server_url }}/${{ github.repository }} .
        fi
        
        echo \"PORT=5000\" > .env
        echo \"TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}\" >> .env
        
        npm install
        
        if ! command -v pm2 &> /dev/null; then
          echo \"PM2 not found, installing...\"
          npm install -g pm2
        fi
        
        if pm2 list | grep -q \"movie-app\"; then
          pm2 restart movie-app
        else
          pm2 start server.js --name \"movie-app\"
        fi
        
        pm2 save
        
        # This part will try to configure PM2 to start on boot
        # But we'll handle it with better error protection
        pm2 startup | grep -q 'sudo' && echo \"PM2 startup requires sudo\" || pm2 startup
        
        echo \"Deployment completed successfully!\"
        "